# Generated by Django 2.2.4 on 2020-01-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200123_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='ItemToIngredient',
        ),
    ]
